CREATE TABLE categories
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(255) NOT NULL
);

CREATE TABLE products
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id          BIGINT         NOT NULL REFERENCES categories (id),
    product_name         VARCHAR(255)   NOT NULL,
    unit_price_amount    NUMERIC(19, 2) NOT NULL,
    unit_price_currency  VARCHAR(3)     NOT NULL
);

CREATE TABLE customers
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name  VARCHAR(255) NOT NULL,
    telephone  VARCHAR(50)  NOT NULL,
    email      VARCHAR(255) NOT NULL UNIQUE,
    address    VARCHAR(255) NOT NULL
);

CREATE TABLE orders
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id    BIGINT                   NOT NULL REFERENCES customers (id),
    status         VARCHAR(20)              NOT NULL,
    total_amount   NUMERIC(19, 2)           NOT NULL,
    total_currency VARCHAR(3)               NOT NULL,
    placed_at      TIMESTAMP WITH TIME ZONE
);

CREATE TABLE order_lines
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id            BIGINT         NOT NULL REFERENCES orders (id),
    product_id          BIGINT         NOT NULL REFERENCES products (id),
    product_name        VARCHAR(255)   NOT NULL,
    quantity            INT            NOT NULL,
    unit_price_amount   NUMERIC(19, 2) NOT NULL,
    unit_price_currency VARCHAR(3)     NOT NULL
);
